"""Keep the existing global data layouts inside the unified topic panel."""
from pathlib import Path
import re
ROOT = Path(__file__).resolve().parents[2]
TOPICS = ('water', 'air', 'soil', 'biodiversity', 'renewables-territory', 'ai-data-centres', 'mining', 'livestock')

def expand(path, parents=()):
    if path in parents:
        return ''  # Browsers ignore an import already on the current stack.
    css = path.read_text()
    def imported(match):
        url = match[1].split('?')[0]
        return expand(ROOT / url.lstrip('/'), parents + (path,))
    return re.sub(r'@import\s+url\([\'\"]([^\'\"]+)[\'\"]\);', imported, css)

def scope(css):
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    out, pos = '', 0
    while pos < len(css):
        op = css.find('{', pos)
        if op < 0:
            break
        head, depth, i = css[pos:op].strip(), 1, op + 1
        while i < len(css) and depth:
            if css[i] == '{': depth += 1
            elif css[i] == '}': depth -= 1
            i += 1
        body = css[op + 1:i - 1]
        if head.startswith(('@media', '@supports', '@layer')):
            out += head + '{' + scope(body) + '}\n'
        elif head.startswith('@'):
            raise ValueError(f'Unsupported CSS rule: {head}')
        else:
            selectors = []
            for sel in head.split(','):
                sel = re.sub(r'(?<![\w-])(:root|html|body)(?![\w-])', '.global-reading', sel.strip())
                sel = sel.replace('#main .inner', '.global-reading').replace('#main', '.global-reading')
                if not sel.startswith('.global-reading'): sel = '.global-reading ' + sel
                selectors.append(sel)
            out += ','.join(selectors) + '{' + body + '}\n'
        pos = i
    return out

for topic in TOPICS:
    source = ROOT / f'assets/css/pages/observatorio-{topic}.css'
    output = ROOT / f'assets/css/pages/unified-{topic}.css'
    output.write_text('/* Generated by scripts/topics/scope-styles.py; edit the source styles. */\n' + scope(expand(source)))
